### PR TITLE
initial import from go-kademlia

### PR DESCRIPTION
**Pull request by guillaumemichel**

### CODE REVIEW

**Comment by guillaumemichel** [comment]
# Go Generics limitations

I am facing serious issues with Go Generics, because they don't provide inheritance properties. 

## Context

### `Point` and `Distance`

For any kind of DHT, nodes and content must be assigned a location (`Point`) in a space/geography (geography can really be anything, from Chord's circle, to Kademlia XOR keyspace, to a N-dimensional non-euclidean geometry). The geography needs to define a `Distance` metric to quantify the separation between any two points in the space, `Distance` is usually a scalar.

For instance, in a 2-dimensional plane a `Point` can be represented by its coordinates `(X, Y)`, and the `Distance` between any two points can be computed as `sqrt( |X1-X0|^2 + |Y1-Y0|^2 )`. Alternatively, the `Distance` could be defined as the [Manhattan distance](https://simple.wikipedia.org/wiki/Manhattan_distance).

In the case of Kademlia, a `Point` is represented by a Bitstring of length `n` and the `Distance` between any two keys is also represented as a Bitstring of length `n`, implying that both the `Point` and the `Distance` can be represented by the same object: `Key`.

### Endpoint

`Endpoint` is a simple module that is responsible for transferring a message from one node to another, and returning any potential response. It can depend on a peer store if needed. It defines a basic interface to send bytes from to a remote node, identified by its `NodeID`.

An example of `Endpoint` could be a libp2p endpoint, depending on the libp2p peer store to find the multiaddress associated with the provided `peer.ID` (implementing `NodeID`). The libp2p endpoint sends the bytes over the network to the remote peer.

Another example of `Endpoint` implementation is the fake endpoint, used in simulations. The fake endpoint will basically transfer the bytes from one node to another in memory, without using the network stack.

## The problem with Go generics

Take the following example:

```go
type Distance[D any] interface {
	Compare(other D) int
}

type Point[P any, D Distance[D]] interface {
	Distance(P) D
	Equal(P) bool
}

// Key is both a Point and a Distance representation, works fine
type Key[K interface {
	Distance[K]
	Point[K, K]
}] interface {
	Distance[K]
	Point[K, K]

	BitLen() int
	Bit(i int) uint
	CommonPrefixLength(other K) int
}

type NodeID[D Distance[D], P Point[P, D]] interface {
	Key() P
}

// all good here
type KadNodeID[K Key[K]] interface {
	NodeID[K, K]
}

type Response[D Distance[D], P Point[P, D], N NodeID[D, P]] interface {
	CloserNodes() []N
}

// still good here
type KadResponse[K Key[K], N NodeID[K]] interface {
	Response[K, K, N]
}

type Request[D Distance[D], P Point[P, D], N NodeID[D, P]] interface {
	Target() P
	EmptyResponse() Response[K, N]
}

// now we want KadRequest to provide a KadResponse for the EmptyResponse() method. However this method must return precisely Response to implement Request. 
type KadRequest[K Key[K], N NodeID[K]] interface {
	Request[K, K, N]
}

type Endpoint[D Distance[D], P Point[P, D], N NodeID[D, P]] interface {
        SendRequest(Request[D, P, N], N) (Response[D, P, N], error)
}

// again, KadEndpoint cannot use KadRequest and KadResponse if it implements Endpoint. Which means that an Endpoint cannot be used to send messages in multiple DHT implementation (Endpoint is just about sending bytes to a Node addressed by its NodeID in the Peer Store.) Endpoint shouldn't rely on Key, Point or Distance but with Go Generics we are stuck :(
type KadEndpoint[K Key[K], N NodeID[K]] interface {
        Endpoint[K, K, N]
}
```

## How we can still go forward?

1. Don't have generic interfaces (e.g `Distance`, `Point` etc.) for all DHTs geographies (Kademlia, Chord, etc.). We define them for each specific DHT geometry, which means that basic primitives (such as `Request`, `Response`, `Endpoint` etc. cannot be reused.
2. Get rids of Go Generics, and cast everywhere to assert the types we are working with. It seems to be the only solution to have proper inheritance and reach genericity, but AFAIU it represents a lot of change in the codebase that @dennis-tra and @iand have made in order to avoid casting at many places.
3. Don't define any additional interfaces for each DHT Geometry and use the generic top level interfaces everywhere. In the example above, if `Key256` is an implementation of the `Key` interface (that wouldn't exist anymore), `Key256` would implement both `Distance` and `Point`. In order to declare a valid `NodeID` we would use `NodeID[Key256, Key256]` (as opposed to `NodeID[Key256]` currently). This solution wouldn't be intuitive for developers that are familiar with (or interested in) a single DHT geometry.
4. Any other suggestion (feel free to edit the comment and add to the list).

TBH I find none of the propositions attractive. Maybe (1) dropping DHT genericity (which was the goal of the go-libdht repo) seems to be the easiest solution.

WDYT @iand @dennis-tra

**Comment by iand** [comment]
Shouldn't the signature of EmptyResponse be as follows?

```Go
type Request[D Distance[D], P Point[P, D], N NodeID[D, P]] interface {
	Target() P
	EmptyResponse() Response[D, P, N]
}
```

**Comment by guillaumemichel** [comment]
> Shouldn't the signature of EmptyResponse be as follows?

@iand yes, you are right, I edited the comment

**Comment by dennis-tra** [comment]
I just had a look at this PR:

- First of all, I don't have a good idea for the embedding problem :/
- In an effort to have a working version that plays together nicely with go-libp2p-kad-dht/v2 I would suggest splitting the migration and introduction of the Point + Distance concepts into two separate steps. This allows us to progress while we figure out the above problems. From what I see, a later addition of `Point` and `Distance` seem to be possible even without breaking `kad` interfaces.
- A general point: Do we know what `Point` and `Distance` could be used for? I understand the desire to abstract it further, especially because we're introducing an even more generic DHT library. I think, in the past, we fell victim to the fact that we were abstracting things without knowing the complete problem space well enough. This time I would suggest only introducing that abstraction as soon as we (or others) work on another DHT type. That will guide us better to find suitable abstractions.
- The commit history still contains 26MB of blobs. I hoped we could reduce that size with this PR. I believe it's the initial commit. However, if we'll squash this PR anyways it's fine.

**Comment by guillaumemichel** [comment]
I agree with @dennis-tra that we can keep further abstractions (such as `Point` and `Distance`) for later, because we need to move on and ship go-libp2p-kad-dht/v2. This would be solution (1) above.

If we proceed with Go Generics (what we had in `go-kademlia`), we won't be able to add any additional top layer abstraction (because of the lack of inheritance of Go Generics), so I am not sure that it makes sense to have `go-libdht`, we could simply keep `go-kademlia` and implement only Kademlia features.

So, I suggest that we delete `go-libdht`, and remove components from `go-kademlia` that will be transferred to `go-libp2p-kad-dht`. We aren't able to achieve genericity without major changes. Let's focus on shipping what is necessary to `go-libp2p-kad-dht/v2`.

**Pull request closed without merging**
